language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"

install:
    - pip install -e git+git://github.com/tomerfiliba/plumbum.git#egg=plumbum

before_script:
    - "pip install paramiko || true"
    - "echo NoHostAuthenticationForLocalhost yes >> ~/.ssh/config"
    - "echo StrictHostKeyChecking no >> ~/.ssh/config"
    - "ssh-keygen -q -f ~/.ssh/id_rsa -N ''"
    - "cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys"
    - "uname -a"
    - "hostname"
    - "python setup.py install"
    - "cd tests"

script: nosetests -vv

notifications:
    email:
        on_success: change
        on_failure: change
