SELECT TOP (1000) [SysMonitoringIIid]
      ,[TimeStamp]
      ,[PercentOfTotalMemory]
      ,[MemoryBytesUsed]
      ,[AveragePercentCPUs]
      ,[CPU0percent]
      ,[CPU1percent]
      ,[CPU2percent]
      ,[CPU3percent]
      ,[CPU4percent]
      ,[CPU5percent]
      ,[CPU6percent]
      ,[CPU7percent]
      ,[Notes]
FROM [LogDB].[dbo].[SysMonitoringLog2]
order by [TimeStamp] desc